name: database_client
description: A base Dart interface for database clients.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.8.0"

dependencies:
  equatable: ^2.0.8
  shared:
    path: ../../shared
  supabase_flutter: ^2.12.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.0.0
