name: powersync_client
description: A package that manages connection to the PowerSync cloud service.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.8.0"
  flutter: ">=3.27.2"

dependencies:
  dio: ^5.9.0
  env:
    path: ../env
  flutter:
    sdk: flutter
  image: ^4.5.4
  path: ^1.9.0
  path_provider: ^2.1.5
  powersync: ^1.17.0
  powersync_core: ^1.7.0
  rxdart: ^0.28.0
  shared:
    path: ../shared
  storage:
    path: ../storage/storage
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
