name: env
description: A package that manages application secrets.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.8.0"
  flutter: ">=3.27.2"

dependencies:
  envied: ^1.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.10.4
  envied_generator: ^1.3.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
