name: persistent_storage
description: Storage that saves data in the device's persistent memory.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.8.0"
  flutter: ">=3.27.2"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^10.0.0
